server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /auth {
        proxy_pass http://${MS_AUTH_HOST}:${MS_AUTH_PORT}/auth;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /eventos {
        proxy_pass http://${MS_EVENTOS_HOST}:${MS_EVENTOS_PORT}/eventos;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /participantes {
        proxy_pass http://${MS_PARTICIPANTES_HOST}:${MS_PARTICIPANTES_PORT}/participantes;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /sorteos {
        proxy_pass http://${MS_SORTEOS_HOST}:${MS_SORTEOS_PORT}/sorteos;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /socket.io/ {
        proxy_pass http://${MS_PARTICIPANTES_HOST}:${MS_PARTICIPANTES_PORT}/socket.io/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 86400s;
    }
}